### PR TITLE
Stub

### PR DESCRIPTION
**Pull request by bam241**
Everything has been changed from `cycamore::xxx` to `recycle::xxx`.

The Cycamore archetypes are not deleted (yet) to make sure tests work properly.

Thanks to @bam241 for great help.

To address issue #1 , an additional PR should be placed deleting all the cycamore archetypes,

which shouldn't be too hard.

### CODE REVIEW

**Comment by bam241** [comment]
ok actually I don't understand why this one don't trigger the test but #5 does :(

**Comment by bam241** [comment]
might be because you where not in the cyclus group

**Comment by jbae11** [comment]
@bam241  interesting.. what do you suggest we do from here?

**Comment by bam241** [comment]
first accept the invitation to join CYclus group member.
then close and reopen the PR ?

**Pull request merged**
