### PR TITLE
stub facility for building

### PR DESCRIPTION
**Pull request by jbae11**
I have added a `stub_facility` for the recycle library to build,

since the build will fail if there are no archetypes to build.

The build succeeded in my machine. Please let me know how it goes.

This will (hopefully) be the final phase of `recycle` initialization, with the previous

archetype histories deleted, and the `cyclus:master` branch building successfully.

The `stub_facility` will eventually be deleted when an actual archetype in development

gets pushed to `cyclus/recycle:master`

### CODE REVIEW

**Comment by katyhuff** [comment]
This seems broken. What's up?
@jbae11

**Comment by jbae11** [comment]
@katyhuff  In the current status, it builds and runs. I have also just fixed the unit test so that it will pass, but since the StubFacility does nothing (prints hello at tick and world at tock), the tests really hold no value. The nosetest fails because it is based on cycamore archetypes. I was hoping the first person who comes up with an archetype will edit the nosetests to fit his/her archetype.

**Comment by katyhuff** [comment]
The nosetests are still failing. We don't pull in failing builds.

**Comment by jbae11** [comment]
@katyhuff  nosetest components were deleted so that the ci passes. I can't really think of another way to make this pass. Do you have any suggestions?

**Comment by katyhuff** [comment]
LGTM

**Comment by katyhuff** [comment]
Why do we need this stub facility at all if it doesn't pass the tests and is just going to be deleted as soon as another facility is made?

**Comment by jbae11** [comment]
I think the whole point was to provide a working template for people to fork and build their archetypes on top of. The stub facility the template that can sort of guide people and get them started by changing few things around, rather than from starting from scratch.

**Comment by katyhuff** [comment]
I know that. In cycamore, the stub facility doesn't cause failed tests, nor does it have to be removed, as suggested above, once other facilities appear.

**Comment by jbae11** [comment]
I'm not sure if I understand. All the tests have passed (that's what github is showing me). Do you want me to delete the stubfacility?

**Comment by katyhuff** [comment]
They only passed because they were deleted halfway through this conversation. Deleting this file (tests/test_run_inputs.py) in particular will disable input checking tests for future archetypes. Deleting the readme (rather than editing it) is also ill-advised. The other file deletions seem like thye're probably ok.

**Comment by katyhuff** [comment]
This still seems to have been handled poorly. @jbae11 , please resolve.

**Review by katyhuff — COMMENTED** [review]
I think this is probably ok to merge. The tests that have been deleted can be added back perhaps as needed.

**Pull request closed without merging**
