### PR TITLE
Recycle Init

### PR DESCRIPTION
**Pull request by jbae11**
Everything has been changed from cycamore::xxx to recycle::xxx.

The Cycamore archetypes are not deleted (yet) to make sure tests work properly.

Thanks to @bam241 for great help.

To address issue #1 , an additional PR should be placed deleting all the cycamore archetypes,

which shouldn't be too hard.

### CODE REVIEW

**Comment by jbae11** [comment]
@bam241  I made a new branch and PR since it seems I can't open/close the previous PRs (nor can I assign reviewers and assignees.. odd)

**Comment by bam241** [comment]
sweet!!

**Comment by bam241** [comment]
@jbae11 I think we can now remove the cycamore archetype within this PR, now that we are sure the test are working properly

**Comment by jbae11** [comment]
okay, @katyhuff suggested we remove the files and git history rather than simply `git rm -` them, 
in case someone were to develop an archetype from a `cycamore` archetype they'd be able to copy the `cycamore` archetypes along with their git history without conflicting with the existing commits for `cycamore` archetypes in this repository.. what do you think @bam241 ?

**Comment by bam241** [comment]
I think she knows better :)

Make sense to me :)

**Comment by jbae11** [comment]
@bam241  should we merge this, and I'll make another PR with the cycamore archetypes deleted!

**Comment by bam241** [comment]
done !

**Pull request merged**
